services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped

    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"

    networks:
      - monitoring

networks:
  monitoring:
    external: true

volumes:
  prometheus-data:
    name: prometheus-data
